blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/jasmine6789/RetailMesh-Cloud-Native-E-commerce-Website/security/policy
    about: Please review our security policy for more details
